### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by silsbyc** [shawnrice/reckoning#4]
Is there a bump to the required php version, too? Seems like this plugin now requires at least 5.4 for the streamlined use of arrays.

**Comment by shawnrice** [comment]
Oh. I must have missed that. I'm running somewhere around `7` and have been off of `5.4` for years now.

I can revert the arrays back to be compatible with php pre `5.4`. Is it just needing to go back to `array()` rather than `[]`?

**Comment by silsbyc** [comment]
I think that is the only roadblock I'm hitting.

**Comment by shawnrice** [comment]
I'll try to roll an update tonight that makes it friendly to older versions of PHP. I'll update here when I do. Thanks for catching, Chris.

**Comment by shawnrice** [comment]
Fixed in 987434925c38a0e3835e91c854d4163407acc6c8 and c5e704a0b6a3d44870f5a2f3d804d17cb1008d68. Pushed to WordPress.org, and version 2.0.1 should be available soon.

**Comment by silsbyc** [comment]
Works again on our system! Thanks for the quick turnaround.
